version: '3'

services:
  smile-gateway:
    image: smile-gateway
    build:
      context: .
      dockerfile: Dockerfile-gateway
    container_name: smile-gateway
    ports:
      - 4000:4000
    networks:
      - community-network
 
networks:
  community-network:
