log-path: Logs.txt

listeners:
- name: listener1
  protocol: 
  address:
    address: 0.0.0.0
    port: 4000
  route-config:
    clusters:
    - user-service
    - auth-service
    - community-service
    - chat-service
  custom-filters:
    - name: ListenerTestFilter
      path: /ApiGateway/CustomFilter.cs
  authorization:
    type: JWT
    login-path: /api/auth/login
    logout-path: /api/user/logout
    jwt-validator:
      valid-audience: http://127.0.0.1:4000
      valid-issuer: http://127.0.0.1:4000
      secret-key: JWTRefreshTokenHIGHsecuredPasswordVVVp1OH7Xzyr
      access-token-validity-in-second: 230400 #64 hours
      refresh-token-validity-in-second: 230400 # 64 hours
  disallow-headers:
    - trace-id
  thread-count: 10

clusters:
  - name: auth-service
    protocol: http
    address:
      - address: 34.22.109.45
        port: 5000
    prefix: /api/auth
    custom-filters:
      - name: ClusterTestFilter
        path: /ApiGateway/ClusterTestFilter.cs
    authorization: false
    connect-timeout: 1000

  - name: user-service
    protocol: http
    address:
      - address: 34.22.109.45
        port: 5000
    prefix: /api/user
    authorization: true
    connect-timeout: 1000

  - name: community-service
    protocol: http
    address:
      - address: 34.22.109.45
        port: 8000
    prefix: /api/community
    custom-filters:
      - name: ClusterTestFilter
        path: /ApiGateway/ClusterTestFilter.cs
    authorization: true
    connect-timeout: 5000
    request-timeout: 20000

  - name: chat-service
    protocol: http
    address:
      - address: 34.22.109.45
        port: 7000
    prefix: /api/chat-service
    custom-filters: 
    authorization: false
    connect-timeout: 5000
    request-timeout: 20000