version: '3'

services:
  node-app:
    build: .
    env_file:
      - .env
    ports:
      - '5000:5000'
      - '2000-2020:2000-2020'
      # - "10000-10100:10000-10100"

    command: npm run start:dev
