version: '3.4'
services:
  kibana:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://10.99.19.2:9200
      - TZ=Asia/Seoul
    ports:
      - 5601:5601
    networks:
      - elasticsearch_efk

networks:
  elasticsearch_efk:
    driver: bridge